# See https://pre-commit.com/ for usage and config
# pre-commit install
# need commit-msg hook for commitzen
# pre-commit install --hook-type commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-vcs-permalinks
    -   id: end-of-file-fixer
        exclude: \.sha256$
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: check-xml
    -   id: check-yaml
    -   id: no-commit-to-branch

-   repo: local
    hooks:
    -   id: verify_checksums
        name: verify checksum
        stages: [commit]
        language: system
        entry: bash scripts/verify_checksums.sh
        files: \.sha256$
